### ISSUE TITLE
Polymorph not working

### ISSUE THREAD

**Issue by MrStatman80** [pr1kol/Oblivion-of-the-Galaxy#1]
With the latest version of the Modpack Polymorph is not working with chest due to Quark maybe backport Quark in next update to fix until Quark fixes

Also any chance for more creative items to make as i got them already

**Comment by pr1kol** [comment]
I will think about solving the problem between the Polymorph and Quark bug. Thx, for your help!

And at the expense of creative things, I do not really understand, you mean that I complicate the crafting of creative items? Or do you want to add craftes for new creative items?

**Comment by pr1kol** [comment]
This bug was fixed in Version 1.9 of Modpack. 
By removing variation chests from the Quark mod.
