### ISSUE TITLE
Found a couple new issues

### ISSUE THREAD

**Issue by MrStatman80** [pr1kol/Oblivion-of-the-Galaxy#2]
Sorry it's me again posting 

But i found a couple of new issues

First is Mob crusher doesn't kill not even passive mobs don't know if it's Foregoing or you disabled but still an issue

Second you have Mystical agriculture in the pack and not all essences as recipes to craft into ingots or what not ie Refine storage Quartz enriched iron and again no idea if disabled or not but no recipes

And Third i meant to have more creative items apart from just Mekanism Creative... What about Pneumaticraft or Botania? creative items?

And last issue is I added silent mechanisms and thermal series to the pack and so recipes doesn't work as not ore dictionary as the Copper, Tin, Iron and Gold is still not unlocked when i had them in my inventory and I have immersive ingots in as well

And sorry again for doing an issue

**Comment by pr1kol** [comment]
Hello, again.

I checked your problems here, I don't have them. Here is a link with video evidence - https://yadi.sk/i/LD0DnKjnUmjmsQ

I also want to note that recipes for creating creative things from mods such as Botania and PneumaticCraft will be added.

And lastly, this is my modpack, and it is fully configured and compatible with other mods in this modpack, and if you install third-party mods in my modpack, then naturally you will have errors and many problems. And then the question is asked, why are you playing it if you are making a stupid modpack out of this project with your mods that make your life easier? Think about it.

I apologize for being rude, but this is just ridiculous.
